# .github/workflows/telegram_bot_workflow.yaml
name: Telegram Bot CI/CD and Cron # Renamed for clarity

on:
  # 1. Trigger on every push to the main branch
  push:
    branches:
      - main  # Only run for pushes to the main branch

  # 2. Trigger on a schedule
  schedule:
    # Cron syntax: Minute Hour Day(month) Month Day(week) (All times UTC)

    # Original schedule (Example: 10:00 AM CEST / 9:00 AM CET)
    # *** ADJUST UTC HOUR based on your current timezone ***
    - cron: '0 13 * * *'

  # 3. Allow manual triggering from the Actions tab (optional but useful)
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.2'

      - name: Installiere Abhängigkeiten
        run: |
          go mod tidy
          go mod vendor
        working-directory: ${{ github.workspace }}

      - name: Build Go Application
        run: go build -o mensaBot .
    
      - name: Run Telegram Bot
        run: ./mensaBot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHATID: ${{ secrets.CHATID }}


